### ISSUE TITLE
Shouldn't we escape \u2028 and \u2029?

### ISSUE THREAD

**Issue by kalekseev** [fusionbox/django-argonauts#16]
The problem http://www.thespanner.co.uk/2011/07/25/the-json-specification-is-now-wrong/
Yahoo serializer escapes these chars https://github.com/yahoo/serialize-javascript/blob/adfee60681dd02b0c4ec73793ad4bb39bbff46ef/index.js#L20

**Comment by gavinwahl** [comment]
The python json serializer already handles this for us:

~~~
>>> print json.dumps(u'\u2028')
"\u2028"
~~~
