### ISSUE TITLE
What does entitize mean?

### ISSUE THREAD

**Issue by graingert** [fusionbox/django-argonauts#20]
in the context of `|json`

**Comment by gavinwahl** [comment]
Replace html special characters with their entities. eg & to &amp; and < to &lt;

I thought this was a standard term but perhaps not.

**Comment by graingert** [comment]
how do you do that?

**Comment by graingert** [comment]
@gavinwahl perhaps a json_a template filter would work

(a for attribute)

**Comment by gavinwahl** [comment]
Project has been deprecated
